openapi: 3.0.3
servers:
  - url: https://lue1i6ic50.execute-api.us-east-1.amazonaws.com/generate-token-api
    description: Live Server
info:
  contact:
    name: Support
    url: info@thegopxtoken.com
  description: Game On Players API
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://thegopxtoken.com/terms-and-conditions
  title: Game On Players API
  version: 1
  x-apisguru-categories:
    - collaboration
    - developer_tools
  x-logo:
    url: https://thegopxtoken.com/wp-content/uploads/2022/03/gopx-logo.png
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
      version: "3.0"
  x-providerName: github.com
externalDocs:
  description: Game On Players API
  url: https://docs.github.com/rest/
paths:
  /approve:
    post:
      summary: Approve 
      description: Approve a certain amount to be transfered/spent from another smart contract 
      parameters:
        - in : header
          name : X-BM-KEY
          schema: string
          required: true 
        - in : header
          name : X-BM-SIGN
          schmea : string
          required: true
        - in: header
          name: client_id
          schema: string
        - in: header
          name: secret_key
          schema: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currency: 
                  type: string
                amount: 
                  type: string
                destination: 
                  type: string
                address: 
                  type: string
                address_memo: 
                  type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  widthdraw_id:
                    type: string
  /price:
    get:
      summary: Get Price 
      description: Get price for GOPX 
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  symbol:
                    type: string
                  last_price:
                    type: string
                  quote_volume_24h:
                    type: string
                  base_volume_24h:
                    type: string
                  high_24h:
                    type: string
                  low_24h:
                    type: string
                  open_24h:
                    type: string
                  close_24h:
                    type: string
                  best_ask:
                    type: string
                  best_ask_size:
                    type: string
                  best_bid:
                    type: string
                  best_bid_size:
                    type: string
                  url:
                    type: string