openapi: 3.0.3
servers:
  - url: http://54.157.246.38:3000
    description: Live Server
info:
  contact:
    name: Support
    url: info@thegopxtoken.com
  description: "# Overview\n The endpoints used in this documents directly creates the necessary elements to interact with the GOPX token. \n\nThis includes: \n\n * creation of wallet \n* price of GOPX token \n* transferring of token"
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://thegopxtoken.com/terms-and-conditions
  title: Game On Players API
  version: 1
  x-apisguru-categories:
    - collaboration
    - developer_tools
  x-logo:
    url: https://thegopxtoken.com/wp-content/uploads/2022/03/gopx-logo.png
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
      version: "3.0"
  x-providerName: github.com
externalDocs:
  description: Game On Players API
  url: https://docs.github.com/rest/
paths:
  /register:
    post:
      summary: Register User
      description: Register user and provide a new wallet for the user to get GOPX Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          content:
            application/json:
              example:
                $ref: "#/components/examples/register"
              schema:
                properties:
                  address:
                    type: string
                  wallet:
                    type: object
                    properties:
                      mnemonic:
                        type: string
                      xpub:
                        type: string
        "400":
          $ref: "#/components/responses/bad_request"
        "404":
          $ref: "#/components/responses/not_found"
        "503":
          $ref: "#/components/responses/service_unavailable"
  /price:
    get:
      summary: Get Price
      description: Get price for GOPX from Bitmart
      responses:
        "200":
          content:
            application/json:
              example:
                $ref: "#/components/examples/price"
              schema:
                properties:
                  symbol:
                    type: string
                  last_price:
                    type: string
                  quote_volume_24h:
                    type: string
                  base_volume_24h:
                    type: string
                  high_24h:
                    type: string
                  low_24h:
                    type: string
                  open_24h:
                    type: string
                  close_24h:
                    type: string
                  best_ask:
                    type: string
                  best_ask_size:
                    type: string
                  best_bid:
                    type: string
                  best_bid_size:
                    type: string
                  url:
                    type: string
        "400":
          $ref: "#/components/responses/bad_request"
        "404":
          $ref: "#/components/responses/not_found"
        "503":
          $ref: "#/components/responses/service_unavailable"
components:
  schemas:
    basic-error:
      description: Basic Error
      properties:
        documentation_url:
          type: string
        message:
          type: string
      title: Basic Error
      type: object
  examples:
    register:
      address: "0xd333de227011ac27656e5f35e7d576827cdff5f2"
      wallet:
        mnemonic: glow can claim above worth daring endless topic obtain crash emotion outside cute toss scare lawn cheap involve infant donkey artwork deer plate agree
        xpub: xpub6Ex6k3D8Qe1KyaSJFUnvqMt2fPsmcgow7pmtMC35jQgYx69dnAQWsE1yregARRdQxFkCUuiKwXzb4x8ht3x2obfgSiMn3aZgSBF7WjBQSfu
    price:
      symbol: "GOPX_USDT"
      last_price: "105.08"
      quote_volume_24h: "114144.6248"
      base_volume_24h: "1096.74"
      high_24h: "105.10"
      low_24h: "102.13"
      open_24h: "103.44"
      close_24h: "105.08"
      best_ask: "105.52"
      best_ask_size: "14.56"
      best_bid: "103.49"
      best_bid_size: "0.14"
      fluctuation: "+0.0159"
      url: "https://www.bitmart.com/trade?symbol=GOPX_USDT"
  responses:
    bad_request:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/basic-error"
      description: Bad Request
    code_scanning_forbidden_write:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/basic-error"
      description: Response if the repository is archived or if github advanced security is not enabled for this repository
    not_found:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/basic-error"
      description: Resource Not Found
    service_unavailable:
      content:
        application/json:
          schema:
            properties:
              code:
                type: string
              documentation_url:
                type: string
              message:
                type: string
            type: object
      description: Service Unavailable
